import cors from '@fastify/cors';
import helmet from '@fastify/helmet';
import fastifyStatic from '@fastify/static';
import Fastify, { type FastifyBaseLogger, type FastifyInstance } from 'fastify';
import type { Knex } from 'knex';
import type { CacheClient } from './cache/redis.js';
import type { ApiEnv } from './env.js';

type ReadinessDb = Pick<Knex, 'raw'>;
type ReadinessCache = Pick<CacheClient, 'ping'>;

export interface AppDependencies {
  env: Pick<ApiEnv, 'CORS_ORIGIN' | 'API_LOG_LEVEL'>;
  db?: ReadinessDb;
  cache?: ReadinessCache;
  logger?: boolean | FastifyBaseLogger;
  adminRoot?: string;
}

export async function buildApp(dependencies: AppDependencies): Promise<FastifyInstance> {
  const app = Fastify({
    logger: dependencies.logger ?? {
      level: dependencies.env.API_LOG_LEVEL
    }
  });

  await app.register(helmet, {
    // The static admin build carries a hash-based CSP meta tag generated by SvelteKit.
    contentSecurityPolicy: false
  });
  await app.register(cors, {
    origin: dependencies.env.CORS_ORIGIN
  });

  if (dependencies.adminRoot) {
    await app.register(fastifyStatic, {
      root: dependencies.adminRoot,
      prefix: '/admin/',
      wildcard: false
    });

    app.get('/admin', async (_request, reply) => reply.redirect('/admin/'));
    app.get('/admin/*', async (_request, reply) => reply.sendFile('index.html'));
  }

  app.get('/health', async () => ({
    status: 'ok'
  }));

  app.get('/ready', async () => {
    await dependencies.db?.raw('select 1');
    await dependencies.cache?.ping();

    return {
      status: 'ready'
    };
  });

  app.get('/v1/ping', async () => ({
    data: {
      message: 'pong'
    }
  }));

  return app;
}
